# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

include:
  - project: dhei/teams/hyperion/dev/src/foundation-build
    file: /pipelines/java-maven-docker-release-pipeline.yaml
    ref: main
  - project: "dhei/teams/hyperion/dev/src/foundation-build"
    file: "/pipelines/opensource-pipeline.yaml"
    ref: main

variables:
  PUSH_TO_HARBOR: "true"
  MTR_TARGET_IMAGE: ${CI_PROJECT_NAME}

build_deploy:
  tags:
    - otc_run_sysbox_m
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  services:
    - name: 'dockerhub.devops.telekom.de/docker:20.10.23-dind'
      command: [ '--tls=false', '--registry-mirror=https://dockerhub.devops.telekom.de' ]
      alias: docker

code_quality:
  tags:
    - otc_run_sysbox_m
  services:
    - name: 'dockerhub.devops.telekom.de/docker:20.10.12-dind'
      command: ['--tls=false', '--host=tcp://0.0.0.0:2375', '--registry-mirror=https://dockerhub.devops.telekom.de']
      alias: docker