################################
# Generic Maven pipeline jobs
# Maintainer: @georg.teichert-matuschek
################################
#
# pipeline variables:
#   MAVEN_OPTS: ...        - optional (default "$MAVEN_OPTS_DEFAULT")
#
# job variables:
#   DOCKER_CONTEXT: ...    - optional for .maven:package-for-docker (default "./docker")
#
# jobs:
#   extends: .maven:package               - runs 'mvn package'
#   extends: .maven:package-for-docker    - runs 'mvn package' and copies the jar as ./$DOCKER_CONTEXT/application.jar
#   extends: .maven:deploy                - runs 'mvn deploy'
#   extends: .maven:test                  - runs 'mvn test'

variables:
  IMAGE_MAVEN:        "maven:3.8.2-openjdk-11-slim"
  MAVEN_OPTS_DEFAULT: "-Dmaven.repo.local=.m2/repository"
  MAVEN_OPTS:         "$MAVEN_OPTS_DEFAULT"
  DOCKER_CONTEXT:     "./docker"

cache:
  key: $CI_PROJECT_PATH_SLUG
  paths:
    - .m2/repository/

.maven:aliases:
  script:
  -  &copy_to_docker
     |
     [[ -z "$DOCKER_CONTEXT" ]] || mkdir -p ${DOCKER_CONTEXT}
     [[ -z "$DOCKER_CONTEXT" ]] || cp $(ls target/*.jar | head -1) ${DOCKER_CONTEXT}/application.jar
     [[ -z "$DOCKER_CONTEXT" ]] || cp $(ls keypair/app.pem | head -1) ${DOCKER_CONTEXT}/app.pem

.maven:basics:
  image: $IMAGE_MAVEN

.maven:package:
  extends: .maven:basics
  script:
    - mvn ${MAVEN_OPTS} package -DskipTests
  artifacts:
    expire_in: 5 mins
    paths:
      - target/*
    

.maven:package-for-docker:
  extends: .maven:package
  after_script:
    - *copy_to_docker
  artifacts:
    paths:
      - ${DOCKER_CONTEXT}

.maven:deploy:
  extends: .maven:basics
  script:
    - mvn ${MAVEN_OPTS} deploy

.maven:test:
  extends: .maven:basics
  script:
    - mvn ${MAVEN_OPTS} test || true

.maven:test_with_sonar:
  extends: .maven:basics
  script:
    - mvn ${MAVEN_OPTS} test || true
    - keytool -import -alias workbench -keystore /etc/pki/java/cacerts -file workbench_utils/ceiser-workbench.cer -storepass changeit -noprompt
    - |
      mvn ${MAVEN_OPTS} sonar:sonar \
        -Dsonar.projectKey=$CI_PROJECT_NAME \
        -Dsonar.host.url=https://ceiser-wbench.psst.t-online.corp/sonar_api \
        -Dsonar.login=$SONAR_TOKEN
    - cat target/site/jacoco/index.html | grep -oP 'Total.*?([0-9]{1,3})%'

  artifacts:
    reports:
      junit: ./target/*-reports/TEST-*.xml
    paths:
      - target/*
