version = 1
SPDX-PackageName = "Gateway Jumper"
SPDX-PackageSupplier = "Deutsche Telekom AG <opensource@telekom.de>"
SPDX-PackageDownloadLocation = "https://github.com/telekom/gateway-jumper"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Deutsche Telekom AG"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "src/test/resources/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Deutsche Telekom AG"
SPDX-License-Identifier = "Apache-2.0"
