server:
  port: 8080

management:
  endpoint:
    gateway.enabled: true # having actuators endpoint for filters e.g. host/actuator/gateway/routefilters
    loggers.enabled: true # having actuators endpoint for setting log level
  endpoints:
    web:
      exposure.include: gateway, loggers, metrics

spring:
  application:
    name: Jumper
  cloud:
    gateway:
      metrics.enabled: true #default ## in order to "push" to prometheus a prometheus dependency is needed in the pom.xml
      default-filters:
        - name: Retry
          args:
            retries: 1
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
            methods: GET,POST,PUT,DELETE,PATCH,HEAD
      httpclient:
        pool:
          type: ELASTIC #default
        connect-timeout: 45000 # default value, ingress 5000
        response-timeout: 120s # ingress 60s
        ssl:
          useInsecureTrustManager: true # routing to a https backend, Gateway will trust all downstream certificates
      x-forwarded:
        for-enabled: true
        for-append: true
        host-enabled: true
        host-append: false
        port-enabled: true
        port-append: false
        proto-enabled: true
        proto-append: false
        prefix-enabled: false
        prefix-append: false
      forwarded:
        enabled: false
  zipkin:
    baseUrl: ${TRACING_URL:https://collector-zipkin-http-drax-guardians.test.dhei.telekom.de}
    #baseUrl: https://collector-zipkin-http-drax-guardians.stage.dhei.telekom.de
  sleuth:
    sampler.probability: 1
    propagation:
      tag.enabled: false

jumper:
  issuer:
    url: ${STARGATE_URL:https://stargate.stage.dhei.telekom.de}/auth/realms
  stargate:
    url: ${STARGATE_URL:https://stargate.stage.dhei.telekom.de}

jumpercache.ttlOffset: 10
jumpercache.cleanCacheInSeconds: 3600

##############################
# local horizon
##############################
horizon:
  publishEventUrl: ${PUBLISH_EVENT_URL:http://producer.stage:8080/v1/events}
  publishEventUrlStargate: ${STARGATE_URL:https://stargate.stage.dhei.telekom.de}/horizon/events/v1
